### ISSUE TITLE
Un client reçoit un email aprés validation de sa réservation

### ISSUE THREAD

**Issue by elgrim312** [AytPlace/Ayt-place#48]
**En tant qu'utilisateur je reçois un mail après la validation de mon offre de location**

**Règles de gestion**

- [x] RG-1: L'utilisateur reçoit un mail pour l'avertir de l'acceptation de son offre de location
 
**Règles d'acceptation**
- [x] RA-1 : En tant qu'utilisateur je reçois un mail quand mon offre de location a été accepté par un bailleur

**Comment by najlabenchelly** [comment]
> **En tant qu'utilisateur je reçois un mail après la validation de mon offre de location**
> 
> **Règles de gestion**
> 
> * [ ]  RG-1: L'utilisateur reçois un mail pour l'avertir de l'acceptation de son offre de location
> 
> **Règles d'acceptation**
> 
> * [ ]  RA-1 : En tant qu'utilisateur je reçois un mail quand mon offre de location a été accepté par un bailleur
